In [177]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [178]:
gdp_g = pd.read_csv('Data/econ_data/GDP_Growth.csv', skiprows=4)
ir = pd.read_csv('Data/econ_data/Inflation_rate.csv', skiprows=4)
gdp_gpc = pd.read_csv('Data/econ_data/GDP_growth_per_capita.csv', skiprows=4)
gcf = pd.read_csv('Data/econ_data/gross_capital_formation.csv', skiprows=4)
igs = pd.read_csv('Data/econ_data/imports_of_goods_and_services.csv', skiprows=4)

In [179]:
gdp_g_89 = gdp_g[['Country Name', 'Country Code', '1989']]
ir_89 = ir[['Country Name', 'Country Code', '1989']]
gdp_gpc_89 = gdp_gpc[['Country Name', 'Country Code', '1989']]
gcf_89 = gcf[['Country Name', 'Country Code', '1989']]
igs_89 = igs[['Country Name', 'Country Code', '1989']]

In [180]:
countries = [
    "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", 
    "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", 
    "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", 
    "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", 
    "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo (Congo-Brazzaville)", 
    "Congo (Democratic Republic of the)", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czechia", "Denmark", 
    "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", 
    "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", 
    "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", 
    "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", 
    "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", 
    "Korea (North)", "Korea (South)", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", 
    "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", 
    "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", 
    "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar (Burma)", "Namibia", 
    "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Macedonia", 
    "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", 
    "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", 
    "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", 
    "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", 
    "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", 
    "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", 
    "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", 
    "United Arab Emirates", "United Kingdom", "United States of America", "Uruguay", "Uzbekistan", 
    "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
]

In [181]:
gdp_g_89 = gdp_g_89[gdp_g_89['Country Name'].isin(countries)]
ir_89 = ir_89[ir_89['Country Name'].isin(countries)]
gdp_gpc_89 = gdp_gpc_89[gdp_gpc_89['Country Name'].isin(countries)]
gcf_89 = gcf_89[gcf_89['Country Name'].isin(countries)]
igs_89 = igs_89[igs_89['Country Name'].isin(countries)]

In [182]:
datasets = [gdp_g_89, ir_89, gdp_gpc_89, gcf_89, igs_89]

for dataset in datasets:
    print(dataset['1989'].isna().sum()/len(dataset['1989']))

0.13690476190476192
0.3392857142857143
0.13690476190476192
0.3392857142857143
0.3392857142857143

In [183]:
north_africa = [
    "Algeria", "Egypt", "Libya", "Morocco", "Tunisia", "Sudan"
]
west_africa = [
    "Benin", "Burkina Faso", "Cape Verde", "Cabo Verde", "Gambia", "Ghana", "Guinea", "Guinea-Bissau", 
    "Ivory Coast", "Liberia", "Mali", "Mauritania", "Niger", "Nigeria", "Senegal", "Sierra Leone", "Togo"
]
central_africa = [
    "Angola", "Cameroon", "Central African Republic", "Chad", "Congo (Congo-Brazzaville)", 
    "Congo (Democratic Republic of the)", "Equatorial Guinea", "Gabon", "Sao Tome and Principe"
]
east_africa = [
    "Burundi", "Comoros", "Djibouti", "Eritrea", "Ethiopia", "Kenya", "Madagascar", "Malawi", "Mauritius", 
    "Mozambique", "Rwanda", "Seychelles", "Somalia", "South Sudan", "Tanzania", "Uganda", "Zambia", "Zimbabwe"
]
southern_africa = [
    "Botswana", "Lesotho", "Namibia", "South Africa", "Eswatini"
]
middle_east = [
    "Bahrain", "Cyprus", "Iran", "Iraq", "Israel", "Jordan", "Kuwait", "Lebanon", "Oman", "Qatar", 
    "Saudi Arabia", "Syria", "Turkey", "United Arab Emirates", "Yemen"
]
central_asia = [
    "Afghanistan", "Kazakhstan", "Kyrgyzstan", "Tajikistan", "Turkmenistan", "Uzbekistan", "Armenia", "Azerbaijan"
]
south_asia = [
    "Bangladesh", "Bhutan", "India", "Maldives", "Nepal", "Pakistan", "Sri Lanka"
]
southeast_asia = [
    "Brunei", "Cambodia", "Indonesia", "Laos", "Malaysia", "Myanmar (Burma)", "Philippines", "Singapore", 
    "Thailand", "Timor-Leste", "Vietnam"
]
east_asia = [
    "China", "Japan", "North Korea", "South Korea", "Taiwan", "Mongolia"
]
eastern_europe = [
    "Belarus", "Bulgaria", "Czechia", "Hungary", "Moldova", "Poland", "Romania", "Russia", "Slovakia", 
    "Ukraine", "Georgia"
]
northern_europe = [
    "Denmark", "Estonia", "Finland", "Iceland", "Ireland", "Latvia", "Lithuania", "Norway", "Sweden", 
    "United Kingdom"
]
southern_europe = [
    "Albania", "Andorra", "Bosnia and Herzegovina", "Croatia", "Greece", "Italy", "Malta", "Montenegro", 
    "North Macedonia", "Portugal", "San Marino", "Serbia", "Slovenia", "Spain", "Vatican City"
]
western_europe = [
    "Austria", "Belgium", "France", "Germany", "Liechtenstein", "Luxembourg", "Monaco", "Netherlands", 
    "Switzerland"
]
central_america = [
    "Belize", "Costa Rica", "El Salvador", "Guatemala", "Honduras", "Nicaragua", "Panama"
]
caribbean = [
    "Antigua and Barbuda", "Bahamas", "Barbados", "Cuba", "Dominica", "Dominican Republic", "Grenada", 
    "Haiti", "Jamaica", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", 
    "Trinidad and Tobago"
]
south_america = [
    "Argentina", "Bolivia", "Brazil", "Chile", "Colombia", "Ecuador", "Guyana", "Paraguay", "Peru", 
    "Suriname", "Uruguay", "Venezuela"
]
north_america = [
    "Canada", "Mexico", "United States of America"
]
oceania = [
    "Australia", "Fiji", "Kiribati", "Marshall Islands", "Micronesia", "Nauru", "New Zealand", 
    "Papua New Guinea", "Samoa", "Solomon Islands", "Tonga", "Tuvalu", "Vanuatu", "Palau"
]

In [184]:
regions = {"north_africa" : north_africa, 
           "west_africa" : west_africa, 
           "central_africa" : central_africa, 
           "east_africa" : east_africa, 
           "southern_africa" : southern_africa,
           "middle_east" : middle_east, 
           "central_asia" : central_asia, 
           "south_asia" : south_asia, 
           "southeast_asia" : southeast_asia, 
           "east_asia" : east_asia, 
           "eastern_europe" : eastern_europe,
           "northern_europe" : northern_europe, 
           "southern_europe" : southern_europe, 
           "western_europe" : western_europe, 
           "central_america" : central_america, 
           "caribbean" : caribbean,
           "south_america" : south_america, 
           "north_america" : north_america,
           "oceania" : oceania}

In [185]:
def classify_region(x):
    for region in regions.keys():
        if x in regions[region]:
            return region

In [186]:
gdp_g_89['Region'] = gdp_g_89['Country Name'].apply(lambda x: classify_region(x))
ir_89['Region'] = ir_89['Country Name'].apply(lambda x: classify_region(x))
gdp_gpc_89['Region'] = gdp_gpc_89['Country Name'].apply(lambda x: classify_region(x))
gcf_89['Region'] = gcf_89['Country Name'].apply(lambda x: classify_region(x))
igs_89['Region'] = igs_89['Country Name'].apply(lambda x: classify_region(x))

In [187]:
for dataset in datasets:
    for region in regions.keys():
        print(region)
        print(dataset[dataset['Region'] == region]['1989'].isna().sum()/len(dataset[dataset['Region'] == region]['1989']))

north_africa
0.0
west_africa
0.0
central_africa
0.0
east_africa
0.16666666666666666
southern_africa
0.0
middle_east
0.0
central_asia
0.5714285714285714
south_asia
0.0
southeast_asia
0.14285714285714285
east_asia
0.0
eastern_europe
0.5555555555555556
northern_europe
0.3
southern_europe
0.5
western_europe
0.0
central_america
0.0
caribbean
0.0
south_america
0.0
north_america
0.0
oceania
0.0
north_africa
0.0
west_africa
0.2857142857142857
central_africa
0.2857142857142857
east_africa
0.4444444444444444
southern_africa
0.2
middle_east
0.36363636363636365
central_asia
1.0
south_asia
0.0
southeast_asia
0.2857142857142857
east_asia
0.3333333333333333
eastern_europe
0.6666666666666666
northern_europe
0.3
southern_europe
0.5
western_europe
0.2222222222222222
central_america
0.14285714285714285
caribbean
0.2222222222222222
south_america
0.18181818181818182
north_america
0.0
oceania
0.38461538461538464
north_africa
0.0
west_africa
0.0
central_africa
0.0
east_africa
0.16666666666666666
southern_africa
0.0
middle_east
0.0
central_asia
0.5714285714285714
south_asia
0.0
southeast_asia
0.14285714285714285
east_asia
0.0
eastern_europe
0.5555555555555556
northern_europe
0.3
southern_europe
0.5
western_europe
0.0
central_america
0.0
caribbean
0.0
south_america
0.0
north_america
0.0
oceania
0.0
north_africa
0.2
west_africa
0.21428571428571427
central_africa
0.2857142857142857
east_africa
0.3888888888888889
southern_africa
0.2
middle_east
0.2727272727272727
central_asia
0.8571428571428571
south_asia
0.14285714285714285
southeast_asia
0.2857142857142857
east_asia
0.0
eastern_europe
0.7777777777777778
northern_europe
0.3
southern_europe
0.5714285714285714
western_europe
0.2222222222222222
central_america
0.0
caribbean
0.4444444444444444
south_america
0.09090909090909091
north_america
0.0
oceania
0.46153846153846156
north_africa
0.2
west_africa
0.14285714285714285
central_africa
0.42857142857142855
east_africa
0.4444444444444444
southern_africa
0.2
middle_east
0.2727272727272727
central_asia
1.0
south_asia
0.14285714285714285
southeast_asia
0.2857142857142857
east_asia
0.0
eastern_europe
0.6666666666666666
northern_europe
0.3
southern_europe
0.5714285714285714
western_europe
0.2222222222222222
central_america
0.0
caribbean
0.4444444444444444
south_america
0.09090909090909091
north_america
0.0
oceania
0.38461538461538464

In [188]:
def impute_data(data):
    region_median = data.groupby('Region')['1989'].median().to_dict()
    for region in regions.keys():
        data.loc[data['Region'] == region, '1989'] = data.loc[data['Region'] == region, '1989'].fillna(region_median[region])
    return data

In [189]:
gdp_g_89 = impute_data(gdp_g_89)
ir_89 = impute_data(ir_89)
gdp_gpc_89 = impute_data(gdp_gpc_89)
gcf_89 = impute_data(gcf_89)
igs_89 = impute_data(igs_89)

In [190]:
igs_89[igs_89['1989'].isna() == True]

     Country Name Country Code  1989        Region
2     Afghanistan          AFG   NaN  central_asia
10        Armenia          ARM   NaN  central_asia
15     Azerbaijan          AZE   NaN  central_asia
120    Kazakhstan          KAZ   NaN  central_asia
234    Tajikistan          TJK   NaN  central_asia
235  Turkmenistan          TKM   NaN  central_asia
252    Uzbekistan          UZB   NaN  central_asia

In [191]:
middle_east_2 = ['Armenia', 'Azerbaijan', 'Kazakhstan', 'Tajikistan', 'Turkmenistan', 'Uzbekistan']

region_median_igs_89 = igs_89.groupby('Region')['1989'].median().to_dict()

igs_89.loc[igs_89['Country Name'] == 'Afghanistan', '1989'] = igs_89.loc[igs_89['Country Name'] == 'Afghanistan', '1989'].fillna(region_median_igs_89['south_asia'])
igs_89.loc[igs_89['Country Name'].isin(middle_east_2) == True, '1989'] = igs_89.loc[igs_89['Country Name'].isin(middle_east_2) == True, '1989'].fillna(region_median_igs_89['middle_east'])

region_median_ir_89 = ir_89.groupby('Region')['1989'].median().to_dict()

ir_89.loc[ir_89['Country Name'] == 'Afghanistan', '1989'] = ir_89.loc[ir_89['Country Name'] == 'Afghanistan', '1989'].fillna(region_median_ir_89['south_asia'])
ir_89.loc[ir_89['Country Name'].isin(middle_east_2) == True, '1989'] = ir_89.loc[ir_89['Country Name'].isin(middle_east_2) == True, '1989'].fillna(region_median_ir_89['middle_east'])

In [192]:
datasets = [gdp_g_89, ir_89, gdp_gpc_89, gcf_89, igs_89]

for dataset in datasets:
    print(dataset['1989'].isna().sum()/len(dataset['1989']))

0.0
0.0
0.0
0.0
0.0

In [193]:
gdp_g_89.rename(columns={'1989': 'gdp_g'}, inplace=True)
ir_89.rename(columns={'1989': 'ir'}, inplace=True)
gdp_gpc_89.rename(columns={'1989': 'gdp_gpc'}, inplace=True)
gcf_89.rename(columns={'1989': 'gcf'}, inplace=True)
igs_89.rename(columns={'1989': 'igs'}, inplace=True)

In [194]:
gdp_g_89 = gdp_g_89.drop(columns=['Region'])
ir_89 = ir_89.drop(columns=['Region'])
gdp_gpc_89 = gdp_gpc_89.drop(columns=['Region'])
gcf_89 = gcf_89.drop(columns=['Region'])
igs_89 = igs_89.drop(columns=['Region'])

In [195]:
econ_data = gdp_g_89.merge(ir_89, on=['Country Name', 'Country Code'])
econ_data = econ_data.merge(gdp_gpc_89, on=['Country Name', 'Country Code'])
econ_data = econ_data.merge(gcf_89, on=['Country Name', 'Country Code'])
econ_data = econ_data.merge(igs_89, on=['Country Name', 'Country Code'])

In [196]:
econ_data

,Country Name,Country Code,gdp_g,ir,gdp_gpc,gcf,igs
0,Afghanistan,AFG,-4.255320,7.844265,-6.798594,35.714286,21.316525
1,Angola,AGO,0.041621,0.689056,-3.274913,0.000000,28.935914
2,Albania,ALB,9.836549,12.686304,6.923617,32.877072,21.472733
3,Andorra,AND,4.827034,12.686304,0.797489,27.005943,23.155419
4,United Arab Emirates,ARE,12.337891,3.342034,5.556954,19.739409,50.621956
...,...,...,...,...,...,...,...
163,Vanuatu,VUT,1.531894,7.748049,-0.988106,30.975828,59.008505
164,Samoa,WSM,3.707314,6.462562,3.439221,23.222904,59.681892
165,South Africa,ZAF,2.394795,14.730918,-0.980961,21.309480,18.992925
166,Zambia,ZMB,-1.023502,123.404255,-3.625652,18.042382,24.932350
167,Zimbabwe,ZWE,5.199766,12.053981,2.233774,15.037981,21.720260

In [197]:
from sklearn.preprocessing import MinMaxScaler

# Example of normalization
scaler = MinMaxScaler()
economic_features = econ_data[['gdp_g', 'ir', 'gdp_gpc', 'gcf', 'igs']]
normalized_features = scaler.fit_transform(economic_features)

In [210]:
econ_data['alpha'] = (0.3 * normalized_features[:, 0] +  # GDP growth
                 0.2 * normalized_features[:, 1] +  # GDP per capita growth
                 0.2 * normalized_features[:, 2] -  # Gross capital formation
                 0.2 * normalized_features[:, 4] -  # Inflation rate
                 0.1 * normalized_features[:, 3])   # Imports of goods and services

In [213]:
econ_data

,Country Name,Country Code,gdp_g,ir,gdp_gpc,gcf,igs,alpha
0,Afghanistan,AFG,-4.255320,7.844265,-6.798594,35.714286,21.316525,0.185701
1,Angola,AGO,0.041621,0.689056,-3.274913,0.000000,28.935914,0.274935
2,Albania,ALB,9.836549,12.686304,6.923617,32.877072,21.472733,0.295473
3,Andorra,AND,4.827034,12.686304,0.797489,27.005943,23.155419,0.263914
4,United Arab Emirates,ARE,12.337891,3.342034,5.556954,19.739409,50.621956,0.291369
...,...,...,...,...,...,...,...,...
163,Vanuatu,VUT,1.531894,7.748049,-0.988106,30.975828,59.008505,0.191910
164,Samoa,WSM,3.707314,6.462562,3.439221,23.222904,59.681892,0.229250
165,South Africa,ZAF,2.394795,14.730918,-0.980961,21.309480,18.992925,0.264037
166,Zambia,ZMB,-1.023502,123.404255,-3.625652,18.042382,24.932350,0.246307
167,Zimbabwe,ZWE,5.199766,12.053981,2.233774,15.037981,21.720260,0.294923